Feature/deepvar recipe
Clinical-Genomics/MIP pull request #1671
Opened 2020-09-16 02:32 UTC by ramprasadn

### This PR adds | fixes:

- Program recipes, pipeline and tests for both DeepVariant and Glnexus

### How to test:

- Automatic and continuous test suite

### Expected outcome:
- [ ] Installation, unit and integration test suite pass

### Review:
- [ ] Code review
- [ ] Tests pass

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes. If applicable record manual test results in PR header
- [ ] **MINOR** - when you add functionality in a backwards compatible manner. If applicable record manual test results in PR header
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

2020-09-17 09:13 UTC, jemten requested changes
Great work Ram! You were definitely thrown into the deep end of the pool directly 😄 
I have added some suggestions and also some questions

2020-09-17 09:13 UTC, jemten commented on lib/MIP/Recipes/Analysis/Glnexus.pm
> +    );
bcftools_view could output a gzipped vcf directly by adding the option `output_type => q{z}`. If you do that you could give bcftools some more threads. That being said, there might be performance benefits to piping through bcftools view without compressing to bgzip as you have written it.

2020-09-17 09:13 UTC, jemten commented on lib/MIP/Recipes/Analysis/Glnexus.pm
> +            write_to_stdout => 1,
Maybe adds some threads to the compression

2020-09-17 11:57 UTC, ramprasadn commented on lib/MIP/Recipes/Analysis/Glnexus.pm
> +    );
I did not find an option to run bcftools view with multiple threads, but bgzip can do that. My guess is that's why authors of glnexus recommend using bgzip for compression. Having said that, bgzip function in MIP as it is, doesn't have that option. So, I'll create a new PR for that.

2020-09-17 12:57 UTC, jemten commented on lib/MIP/Recipes/Analysis/Glnexus.pm
> +    );
I think it's a rather new addition to [bcftools](http://samtools.github.io/bcftools/bcftools.html#view). You just add --threads to the bcftools command. Maybe there's no support for it in MIP yet. Anyway it's perfectly fine to use bgzip as well

2020-09-21 06:15 UTC, henrikstranneheim approved these changes
Well done RAM!

2020-09-21 06:15 UTC, henrikstranneheim commented on lib/MIP/Program/Glnexus.pm
> +##          : $infile_paths_ref            => Space separated list of input vcf files
Align fat comma

2020-09-21 06:15 UTC, henrikstranneheim commented on lib/MIP/Recipes/Analysis/Deepvariant.pm
> +    use MIP::Get::Parameter qw{get_recipe_attributes  get_recipe_resources };
```suggestion
    use MIP::Get::Parameter qw{ get_recipe_attributes  get_recipe_resources };
```

2020-09-21 06:15 UTC, henrikstranneheim commented on lib/MIP/Recipes/Analysis/Deepvariant.pm
> +            outfile_path       => $outfile_path,
Order args AB (alphabetically)

2020-09-21 06:15 UTC, henrikstranneheim commented on lib/MIP/Recipes/Analysis/Glnexus.pm
> +            config           => $config_type,
Order AB

2020-09-21 06:15 UTC, henrikstranneheim commented on lib/MIP/Recipes/Pipeline/Analyse_rd_dna.pm
> +    use MIP::Recipes::Analysis::Glnexus qw{ analysis_glnexus };
Order AB

2020-10-05 13:28 UTC, ramprasadn commented on lib/MIP/Recipes/Analysis/Glnexus.pm
> +        $analysis_type = $active_parameter_href->{analysis_type}{$sample_id};
I have actually resolved this issue in the latest commit. Just forgot to mark it here as such.

2020-10-06 10:03 UTC, jemten reviewed
Great work Ram! Almost there  😄 .I added som minor comments. Also there is a check failure on github actions.

2020-10-06 10:03 UTC, jemten commented on templates/mip_install_config.yaml
> +    uri: docker.io/google/deepvariant:1.0.0
Woho! 🥳

2020-10-07 07:45 UTC, jemten approved these changes
👍

2020-10-07 08:10 UTC, merged

2020-10-07 11:24 UTC, henrikstranneheim commented
@ramprasadn Great work! Looks like there was a slight drop in coverage. Seems like you should add some more test to the glnexus recipe in a future PR