uncouple deepvariant from gatk combinevariants
Clinical-Genomics/MIP pull request #1843
Opened 2021-03-15 17:18 UTC by ramprasadn

### This PR adds | fixes:

- see above

### How to test:

- Automatic and continuous test suite

### Expected outcome:
- [ ] Installation, unit and integration test suite pass

### Review:
- [ ] Code review
- [ ] Tests pass

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes. If applicable record manual test results in PR header
- [x] **MINOR** - when you add functionality in a backwards compatible manner. If applicable record manual test results in PR header
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

2021-03-16 09:40 UTC, henrikstranneheim requested changes
Looks good! But I think we should use a "temporary" CLI switch.

2021-03-16 09:40 UTC, henrikstranneheim commented on lib/MIP/Recipes/Analysis/Gatk_combinevariantcallsets.pm
> +    push @variant_callers, q {gatk_variantrecalibration};
I think you should make a CLI switch for this instead of comment out the code

2021-03-16 09:40 UTC, henrikstranneheim commented on lib/MIP/Recipes/Analysis/Glnexus.pm
> +                path             => $outfile_path_prefix . q{.vcf.gz},
Looks like outfile_path uses temp. Unless the files are moved the temp files will be deleted and not available for donwstream processes.

2021-03-16 09:40 UTC, henrikstranneheim commented on lib/MIP/Recipes/Pipeline/Analyse_rd_dna.pm
> +    ##  );
Add same CLI switch

2021-03-16 09:40 UTC, henrikstranneheim commented on lib/MIP/Recipes/Pipeline/Analyse_rd_dna_panel.pm
> +    ## );
Add same CLI switch

2021-03-22 14:00 UTC, ramprasadn commented on lib/MIP/Recipes/Analysis/Glnexus.pm
> +                path             => $outfile_path_prefix . q{.vcf.gz},
Recipe worked as intended, but I think the naming of the variable was not very clear. I have fixed it now.

2021-03-22 14:01 UTC, ramprasadn commented on lib/MIP/Recipes/Analysis/Gatk_combinevariantcallsets.pm
> +    push @variant_callers, q {gatk_variantrecalibration};
Its fixed now. Let me know what you think.

2021-03-23 07:17 UTC, henrikstranneheim approved these changes
👍

2021-03-23 09:40 UTC, merged